version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb://mongoadmin:mongopass@localhost:27017/course-goals?authSource=admin'
      AUTH_API_ADDRESSS: 'auth:3000'